"""added report tables

Revision ID: 71dcaa412f6b
Revises: 075e10c3a6f7
Create Date: 2025-11-05 23:54:13.968594

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71dcaa412f6b"
down_revision = "075e10c3a6f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("total_todos", sa.Integer(), nullable=False),
        sa.Column("completed_todos", sa.Integer(), nullable=False),
        sa.Column("skipped_todos", sa.Integer(), nullable=False),
        sa.Column("incomplete_todos", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_id"), "reports", ["id"], unique=False)
    op.create_table(
        "task_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("todo_id", sa.Integer(), nullable=False),
        sa.Column("todo_title", sa.String(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=False),
        sa.Column(
            "final_status",
            sa.Enum(
                "incomplete", "in_progress", "complete", "skipped", name="taskstatus"
            ),
            nullable=False,
        ),
        sa.Column("in_progress_duration_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_reports_id"), "task_reports", ["id"], unique=False)
    op.add_column("todos", sa.Column("in_progress_start", sa.DateTime(), nullable=True))
    op.add_column(
        "todos", sa.Column("cumulative_in_progress_seconds", sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "cumulative_in_progress_seconds")
    op.drop_column("todos", "in_progress_start")
    op.drop_index(op.f("ix_task_reports_id"), table_name="task_reports")
    op.drop_table("task_reports")
    op.drop_index(op.f("ix_reports_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
