"""initial_migration

Revision ID: 9d10c29f55c6
Revises:
Create Date: 2025-11-05 19:49:27.839127

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "9d10c29f55c6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Initial migration that handles existing databases gracefully.

    Since this project switched to Alembic mid-development, this migration
    checks if tables already exist before attempting to create them.
    If all tables exist, this migration is essentially a no-op, allowing
    Alembic to mark it as applied without errors.
    """
    # Get database connection and inspector
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()

    # Create categories table if it doesn't exist
    if "categories" not in existing_tables:
        op.create_table(
            "categories",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("description", sa.String(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
        op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)

    # Create oneoff_todos table if it doesn't exist
    if "oneoff_todos" not in existing_tables:
        op.create_table(
            "oneoff_todos",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("title", sa.String(), nullable=False),
            sa.Column("description", sa.String(), nullable=True),
            sa.Column(
                "status",
                sa.Enum("incomplete", "in_progress", "complete", name="taskstatus"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_oneoff_todos_id"), "oneoff_todos", ["id"], unique=False
        )

    # Create todos table if it doesn't exist
    if "todos" not in existing_tables:
        op.create_table(
            "todos",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("title", sa.String(), nullable=False),
            sa.Column("description", sa.String(), nullable=True),
            sa.Column(
                "status",
                sa.Enum("incomplete", "in_progress", "complete", name="taskstatus"),
                nullable=False,
            ),
            sa.Column("category_id", sa.Integer(), nullable=False),
            sa.Column("reset_interval", sa.Integer(), nullable=False),
            sa.Column("reset_count", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["category_id"],
                ["categories.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_todos_id"), "todos", ["id"], unique=False)

    # Create todo_dependencies table if it doesn't exist
    if "todo_dependencies" not in existing_tables:
        op.create_table(
            "todo_dependencies",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("todo_id", sa.Integer(), nullable=False),
            sa.Column("depends_on_todo_id", sa.Integer(), nullable=True),
            sa.Column("depends_on_category_id", sa.Integer(), nullable=True),
            sa.Column("depends_on_all_oneoffs", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["depends_on_category_id"], ["categories.id"], ondelete="CASCADE"
            ),
            sa.ForeignKeyConstraint(
                ["depends_on_todo_id"], ["todos.id"], ondelete="CASCADE"
            ),
            sa.ForeignKeyConstraint(["todo_id"], ["todos.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_todo_dependencies_id"), "todo_dependencies", ["id"], unique=False
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todo_dependencies_id"), table_name="todo_dependencies")
    op.drop_table("todo_dependencies")
    op.drop_index(op.f("ix_todos_id"), table_name="todos")
    op.drop_table("todos")
    op.drop_index(op.f("ix_oneoff_todos_id"), table_name="oneoff_todos")
    op.drop_table("oneoff_todos")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
