"""removed dep tables

Revision ID: ee900e1af34c
Revises: dcefd4932568
Create Date: 2025-11-09 10:27:00.196055

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee900e1af34c"
down_revision = "dcefd4932568"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_oneoff_todo_dependencies_computed_id"),
        table_name="oneoff_todo_dependencies_computed",
    )
    op.drop_table("oneoff_todo_dependencies_computed")
    op.drop_index(op.f("ix_todo_dependencies_id"), table_name="todo_dependencies")
    op.drop_table("todo_dependencies")
    op.drop_index(
        op.f("ix_oneoff_todo_dependencies_id"), table_name="oneoff_todo_dependencies"
    )
    op.drop_table("oneoff_todo_dependencies")
    op.drop_index(
        op.f("ix_todo_dependencies_computed_id"),
        table_name="todo_dependencies_computed",
    )
    op.drop_table("todo_dependencies_computed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_dependencies_computed",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("todo_id", sa.INTEGER(), nullable=False),
        sa.Column("depends_on_todo_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_todo_id"], ["todos.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["todo_id"], ["todos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_todo_dependencies_computed_id"),
        "todo_dependencies_computed",
        ["id"],
        unique=False,
    )
    op.create_table(
        "oneoff_todo_dependencies",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("depends_on_todo_id", sa.INTEGER(), nullable=True),
        sa.Column("depends_on_category_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["depends_on_category_id"], ["categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_todo_id"], ["todos.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oneoff_todo_dependencies_id"),
        "oneoff_todo_dependencies",
        ["id"],
        unique=False,
    )
    op.create_table(
        "todo_dependencies",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("todo_id", sa.INTEGER(), nullable=False),
        sa.Column("depends_on_todo_id", sa.INTEGER(), nullable=True),
        sa.Column("depends_on_category_id", sa.INTEGER(), nullable=True),
        sa.Column("depends_on_all_oneoffs", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_category_id"], ["categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_todo_id"], ["todos.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["todo_id"], ["todos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_todo_dependencies_id"), "todo_dependencies", ["id"], unique=False
    )
    op.create_table(
        "oneoff_todo_dependencies_computed",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("depends_on_todo_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_todo_id"], ["todos.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oneoff_todo_dependencies_computed_id"),
        "oneoff_todo_dependencies_computed",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###
