"""simplify_dependencies_to_node_only

Revision ID: 10ff48682be0
Revises: 9d10c29f55c6
Create Date: 2025-11-05 20:03:37.822186

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10ff48682be0"
down_revision = "9d10c29f55c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add position column to todos with default value
    op.add_column("todos", sa.Column("position", sa.Integer(), nullable=False, server_default="0"))

    # SQLite doesn't support ALTER COLUMN, so we need to use batch mode to recreate the table
    with op.batch_alter_table("todo_dependencies", schema=None) as batch_op:
        # Add is_explicit column
        batch_op.add_column(sa.Column("is_explicit", sa.Integer(), nullable=False, server_default="1"))

        # Drop the old columns
        batch_op.drop_column("depends_on_all_oneoffs")
        batch_op.drop_column("depends_on_category_id")

        # Alter depends_on_todo_id to be NOT NULL
        batch_op.alter_column("depends_on_todo_id", existing_type=sa.INTEGER(), nullable=False)

    # Delete all existing dependencies - they will be regenerated from config with expanded categories
    op.execute("DELETE FROM todo_dependencies")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop position column from todos
    op.drop_column("todos", "position")

    # Recreate the old todo_dependencies structure
    with op.batch_alter_table("todo_dependencies", schema=None) as batch_op:
        # Add back the old columns
        batch_op.add_column(sa.Column("depends_on_category_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("depends_on_all_oneoffs", sa.INTEGER(), nullable=False, server_default="0"))

        # Make depends_on_todo_id nullable again
        batch_op.alter_column("depends_on_todo_id", existing_type=sa.INTEGER(), nullable=True)

        # Drop is_explicit column
        batch_op.drop_column("is_explicit")

        # Recreate foreign key
        batch_op.create_foreign_key(
            "fk_depends_on_category", "categories", ["depends_on_category_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###
