"""add_two_dependency_tables

Revision ID: 2a2c3fcdf25e
Revises: 9d10c29f55c6
Create Date: 2025-11-05 20:20:55.361975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2c3fcdf25e'
down_revision = '9d10c29f55c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_dependencies_computed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_todo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_dependencies_computed_id'), 'todo_dependencies_computed', ['id'], unique=False)
    op.add_column('todos', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'position')
    op.drop_index(op.f('ix_todo_dependencies_computed_id'), table_name='todo_dependencies_computed')
    op.drop_table('todo_dependencies_computed')
    # ### end Alembic commands ###
