"""initial_migration

Revision ID: 9d10c29f55c6
Revises:
Create Date: 2025-11-05 19:49:27.839127

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d10c29f55c6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)

    op.create_table(
        "oneoff_todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.Enum("incomplete", "in_progress", "complete", name="taskstatus"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oneoff_todos_id"), "oneoff_todos", ["id"], unique=False)

    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.Enum("incomplete", "in_progress", "complete", name="taskstatus"), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("reset_interval", sa.Integer(), nullable=False),
        sa.Column("reset_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todos_id"), "todos", ["id"], unique=False)

    op.create_table(
        "todo_dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("todo_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_todo_id", sa.Integer(), nullable=True),
        sa.Column("depends_on_category_id", sa.Integer(), nullable=True),
        sa.Column("depends_on_all_oneoffs", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["depends_on_category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["depends_on_todo_id"], ["todos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["todo_id"], ["todos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todo_dependencies_id"), "todo_dependencies", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todo_dependencies_id"), table_name="todo_dependencies")
    op.drop_table("todo_dependencies")
    op.drop_index(op.f("ix_todos_id"), table_name="todos")
    op.drop_table("todos")
    op.drop_index(op.f("ix_oneoff_todos_id"), table_name="oneoff_todos")
    op.drop_table("oneoff_todos")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
