"""oneoff dependancys

Revision ID: dcefd4932568
Revises: 71dcaa412f6b
Create Date: 2025-11-07 01:41:11.335559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcefd4932568'
down_revision = '71dcaa412f6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oneoff_todo_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depends_on_todo_id', sa.Integer(), nullable=True),
    sa.Column('depends_on_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oneoff_todo_dependencies_id'), 'oneoff_todo_dependencies', ['id'], unique=False)
    op.create_table('oneoff_todo_dependencies_computed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depends_on_todo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oneoff_todo_dependencies_computed_id'), 'oneoff_todo_dependencies_computed', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oneoff_todo_dependencies_computed_id'), table_name='oneoff_todo_dependencies_computed')
    op.drop_table('oneoff_todo_dependencies_computed')
    op.drop_index(op.f('ix_oneoff_todo_dependencies_id'), table_name='oneoff_todo_dependencies')
    op.drop_table('oneoff_todo_dependencies')
    # ### end Alembic commands ###
