---
name: backend-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3.2.0
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: prepare variables
        id: ev
        shell: python
        run: |
          """Helper script to get the actual branch name, docker safe"""
          import os

          sha = os.environ["GITHUB_SHA"] if not "${{ github.event.pull_request.head.sha }}" else "${{ github.event.pull_request.head.sha }}"

          with open(os.environ["GITHUB_OUTPUT"], "a+", encoding="utf-8") as _output:
              print("sha=%s" % sha, file=_output)
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/ripplefcl/taskin-backend:${{ steps.ev.outputs.sha }},
            ghcr.io/ripplefcl/taskin-backend:latest
          platforms: linux/amd64,linux/arm64
          context: taskin-api
          build-args: |
            GIT_BUILD_HASH=${{ steps.ev.outputs.sha }}
